day16/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app01.views import depart, user, pretty, admin, account, task, order

urlpatterns = [
    # path('admin/', admin.site.urls),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 靓号管理
    path('prettynum/list/', pretty.prettynum_list),
    path('prettynum/add/', pretty.prettynum_add),
    path('prettynum/<int:nid>/edit/', pretty.prettynum_edit),
    path('prettynum/<int:nid>/delete/', pretty.prettynum_delete),

    # 管理员的管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),

]

app01/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="姓名", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")

    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
    gender_choices = (
        (1, "男"),
        (2, "女")
    )

    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    mobile = models.CharField(max_length=50, verbose_name='手机号')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格')

    LEVEL_CHOICES = (
        (1, '一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级'),
    )
    level = models.IntegerField(choices=LEVEL_CHOICES, verbose_name='级别')

    STATUS_CHOICES = (
        (1, '未占用'),
        (2, '已占用'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, verbose_name='状态')


class Task(models.Model):
    """任务"""
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)


class Order(models.Model):
    """订单"""
    STATUS_CHOICES = (
        (1, "已支付"),
        (2, "待支付"),
    )

    oid = models.CharField(verbose_name="订单号", max_length=50)
    title = models.CharField(verbose_name="商品名称", max_length=100)
    price = models.DecimalField(verbose_name="价格", max_digits=10, decimal_places=2)
    status = models.SmallIntegerField(verbose_name="状态", choices=STATUS_CHOICES, default=2)
    admin = models.ForeignKey(Admin, verbose_name="管理员", on_delete=models.CASCADE)

    def __str__(self):
        return self.oid

    class Meta:
        verbose_name = "订单"
        verbose_name_plural = "订单"

app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms

from app01 import models
from app01.utils.bootstrap import BootStrapForm, BootStrapModelForm
from app01.utils.encrypt import md5


class LoginForm(BootStrapForm):
    username = forms.CharField(label="用户名", widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="密码",
                               widget=forms.PasswordInput(attrs={"class": "form-control"}, render_value=True))
    code = forms.CharField(label="验证码",
                           widget=forms.TextInput(attrs={"class": "form-control"}))

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # {'username': 'erog', 'password': 'boigi'}
        # print(form.cleaned_data)
        # {'username': 'erog', 'password': 'b9eac0d4fc8c0220b6cb4dbb02284892'}

        # 验证码的校验，从form.cleaned_data中剔除式校验
        user_input_code = form.cleaned_data.pop('code')  # 而不是用get
        code = request.session.get('image_code', '')  # 可能为空 ，因为设置了60s超时
        if code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")  # 把错误信息展示到密码框下面了
            return render(request, 'login.html', {"form": form})   # 后面代码就不会执行了

        # 去数据库校验用户名和密码是否正确,获取用户对象
        # admin_object = models.Admin.objects.filter(username="xxx", password="xxx").first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")  # 把错误信息展示到密码框下面了
            return render(request, 'login.html', {"form": form})  # 会直接返回验证码错误；

        # 用户名和密码正确,登录成功后
        # 网站生成随机字符串;写到用户浏览器的cookie中;再写入到session中；
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        # 登录成功并且设置了在session中设置了用户信息之后，session可以保存七天
        request.session.set_expiry(60*60*24*7)

        return redirect("/admin/list/")

    return render(request, 'login.html', {"form": form})


def logout(request):
    """注销"""

    request.session.clear()

    return redirect("/login/")


from app01.utils.code import check_code
from io import BytesIO


def image_code(request):
    """生成图片验证码"""

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码在进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s超时
    request.session.set_expiry(60)

    image_stream = BytesIO()
    img.save(image_stream, format='PNG')

    return HttpResponse(image_stream.getvalue())

app01/views/admin.py
from django.shortcuts import render, redirect

from app01.utils.pagination import Pagination
from app01 import models


def admin_list(request):
    """ 管理员列表 """
    # 检查用户是否已经登录，已登录，继续往下走，未登录，跳转回登录页面。
    # 用户发来请求，获取cookie随机发来的字符串，拿着随机字符串看看session中有没有，有的话，说明以前登录过;
    # info = request.session.get("info")
    # print(info)
    # # {'id': 7, 'name': 'eric'}
    # # 删除浏览器中的cookie中的数据 ----------- None 登录状态已经删除
    # if not info:
    #     return redirect('/login/')  # 没有登录，返回登录页面

    # 构造搜索
    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["username__contains"] = search_data
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_object = Pagination(request, queryset)
    page_queryset = page_object.page_queryset
    page_string = page_object.html()

    context = {
        "queryset": page_queryset,
        "search_data": search_data,
        "page_string": page_string
    }

    return render(request, 'admin_list.html', context)


from django import forms
from django.core.exceptions import ValidationError
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.encrypt import md5


class AdminModelForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'in', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(render_value=True, attrs={'class': 'in', 'placeholder': 'Password'})
    )
    confirm_password = forms.CharField(label="确认密码",
                                       widget=forms.PasswordInput(render_value=True))

    class Meta:
        model = models.Admin
        fields = '__all__'

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致，请重新输入")
        return confirm


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


class AdminResetModelForm(BootStrapModelForm):
    password = forms.CharField(widget=forms.PasswordInput(render_value=True))
    confirm_password = forms.CharField(label="确认密码",
                                       widget=forms.PasswordInput(render_value=True))

    class Meta:
        model = models.Admin
        fields = ["password", "confirm_password"]

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        md5_pwd = md5(pwd)

        # 去数据库校验当前密码和新输入的密码是否一致
        exists = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exists:
            raise ValidationError("密码不能与以前的密码相同")

        return md5_pwd

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致，请重新输入")
        return confirm


def admin_add(request):
    """添加管理员"""
    title = "新建管理员"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change.html', {"form": form, "title": title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {"form": form, "title": title})


def admin_edit(request, nid):
    """ 编辑管理员 """
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        # 错误提示
        # return render(request, 'error.html', {"msg": "数据不存在"})
        return redirect('/admin/list/')

    title = "编辑管理员"
    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {"form": form, "title": title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)  # 有了instance使得不是添加而是修改
    if form.is_valid():
        print(form.cleaned_data)
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {"form": form, "title": title})  # 返回错误信息


def admin_delete(request, nid):
    """删除管理员"""
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    """重置密码"""
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        # 错误提示
        # return render(request, 'error.html', {"msg": "数据不存在"})
        return redirect('/admin/list/')

    title = "重置密码 - {}".format(row_object.username)

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, 'change.html', {"form": form, "title": title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'change.html', {"form": form, "title": title})

app01/views/depart.py
from django.shortcuts import render, redirect
from app01.utils.pagination import Pagination
from app01 import models
from app01.utils.forms import UserModelForm, PrettyNumForm, PrettyNumEditForm


# Create your views here.

def depart_list(request):
    """ 部门列表 """
    # 去数据库中获取所有的部门列表
    # [对象，对象，对象
    queryset = models.Department.objects.all()

    page_object = Pagination(request, queryset, page_size=2)

    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html()
    }
    return render(request, "depart_list.html", context)


def depart_add(request):
    """ 添加部门 """
    if request.method == "GET":
        return render(request, 'depart_add.html')

    # 获取用户POST提交过来的数据  (title输入为空)
    title = request.POST.get("title")

    # 保存到数据库
    models.Department.objects.create(title=title)

    # 重定向回部门列表
    return redirect("/depart/list/")


def depart_delete(request):
    """ 删除部门 """
    # 获取ID
    nid = request.GET.get("nid")

    # 删除
    models.Department.objects.filter(id=nid).delete()

    # 重定向
    return redirect("/depart/list")


def depart_edit(request, nid):
    """ 修改部门 """
    if request.method == "GET":
        # 根据nid,获取它的数据[odj,]
        row_object = models.Department.objects.filter(id=nid).first()

        return render(request, 'depart_edit.html', {"row_object": row_object})

    # 获取用户POST提交过来的数据  (title输入为空)
    newtitle = request.POST.get("title")

    # 保存到数据库
    models.Department.objects.filter(id=nid).update(title=newtitle)

    # 重定向回部门列表
    return redirect("/depart/list/")

app01/views/order.py
import random
from datetime import datetime
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))


class OrderModelForm(BootStrapModelForm):
    class Meta:
        model = models.Order
        # fields = "__all__"
        exclude = ["oid", "admin"]


def order_list(request):
    queryset = models.Order.objects.all().order_by("-id")
    page_object = Pagination(request, queryset)

    page_queryset = page_object.page_queryset
    page_string = page_object.html()
    form = OrderModelForm()

    context = {
        "form": form,  # 用于生成模态框的输入元素
        # 用于实现表格和分页
        "queryset": page_queryset,  # 分完页的数据
        # "search_data": search_data,
        "page_string": page_string  # 生成页码
    }

    return render(request, 'order_list.html', context)


@csrf_exempt
def order_add(request):
    """新建订单（Ajax请求）"""
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        # 订单号: 额外增加一些不是用户输入的值(自己计算出来)
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
        form.instance.admin_id = request.session["info"]["id"]

        # 保存到数据库
        form.save()
        return JsonResponse({"status": True})
        # return HttpResponse(json.dumps({"status": True}))

    return JsonResponse({"status": False, 'error': form.errors})


def order_delete(request):
    """ 删除订单 """
    uid = request.GET.get("uid")
    models.Order.objects.filter(id=uid).delete()
   

app01/views/pretty.py
from django.shortcuts import render, redirect
from app01.utils.pagination import Pagination
from app01 import models
from app01.utils.forms import UserModelForm, PrettyNumForm, PrettyNumEditForm


# Create your views here.


def prettynum_list(request):
    """ 靓号列表 """

    get_object = request.GET.copy()  # 复制QueryDict对象，产生一个可修改的副本
    # 修改副本中的参数值
    # get_object.setlist('page', [11])
    # 获取修改后的URL编码字符串
    # encoded_object = get_object.urlencode()
    # print(encoded_object)

    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["mobile__contains"] = search_data

    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-level")

    page_object = Pagination(request, queryset)

    page_queryset = page_object.page_queryset
    page_string = page_object.html()

    context = {
        "queryset": page_queryset,  # 分完页的数据
        "search_data": search_data,
        "page_string": page_string  # 页码
    }

    return render(request, 'prettynum_list.html', context)


def prettynum_add(request):
    if request.method == "GET":
        form = PrettyNumForm()
        return render(request, 'prettynum_add.html', {"form": form})

    form = PrettyNumForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/prettynum/list/")
    return render(request, 'prettynum_add.html', {"form": form})


def prettynum_edit(request, nid):
    if request.method == "GET":
        row_object = models.PrettyNum.objects.filter(id=nid).first()
        form = PrettyNumEditForm(instance=row_object)
        return render(request, "prettynum_edit.html", {"form": form})

    else:
        row_object = models.PrettyNum.objects.filter(id=nid).first()
        form = PrettyNumEditForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect("/prettynum/list/")
        else:
            return render(request, "prettynum_edit.html", {"form": form})


def prettynum_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect("/prettynum/list/")

app01/templates/change.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">{{ title }}</div>
                <div class="panel-body">
                    <form class="form-group" method="post" novalidate>  <!--把浏览器做的校验给关掉-->
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <!--<input type="text" class="form-control" placeholder="姓名" name="user"/>-->
                                <span style="color: red;">{{ field.errors.0 }}</span>
                                <!--有错误信息才执行 错误信息可能特别多[错误1，错误2……],取第一条-->
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                todayHighlight: true,
                language: "zh-CN",
                autoclose: true
            });

        })
    </script>
{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}


{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <input type="button" value="新建订单1" class="btn btn-primary" data-toggle="modal" data-target="#myModal">

            <input id="btnAdd" type="button" value="新建订单2" class="btn btn-primary">
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>

            <table class="table table-bordered">

                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>名称</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>管理员</th>
                    <th>操作</th>
                </tr>
                </thead>

                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                            <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button"
                                   value="删除">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>

    </div>

    <!-- Modal 新建订单（对话框） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd" class="form-group">  <!--把浏览器做的校验给关掉-->
                        {% csrf_token %}
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative; margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <!--<input type="text" class="form-control" placeholder="姓名" name="user"/>-->
                                        <span class="error-msg"
                                              style="color: red;position: absolute">{{ field.errors.0 }}</span>
                                        <!--有错误信息才执行 错误信息可能特别多[错误1，错误2……],取第一条-->
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 删除（对话框）-->
    <div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>是否确定删除？</h4>
                <p style="margin:10px 0;"> 删除后，所有关联的相关数据都会被删除。</p>
                <p style="text-align:right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        //声明全局变量
        var DELETE_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                // 点击新建按钮，显示对话框
                $('#myModal').modal('show')
            });
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                //alert("保存")
                //清除错误信息
                $(".error-msg").empty();

                //向后台发送请求
                $.ajax({
                    url: "/order/add/",
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("创建成功")
                            // 清空表单 $("#formAdd")是jQuery对象 -> $("#formAdd")[0] DOM对象
                            $("#formAdd")[0].reset();

                            // 关闭对话框
                            $('#myModal').modal('hide')

                            // 刷新页面，使得在表格中展示新添加的数据
                            location.reload()

                        } else {
                            // 把错误信息显示到模态对话框的相应位置
                            $.each(res.error, function (name, errorList) {
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }
                    }
                })
            });
        }

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                // 点击新建按钮，显示对话框
                $('#deleteModel').modal('show');

                // 获取当前行的ID并赋值给全局变量。
                DELETE_ID = $(this).attr("uid");
                console.log(uid);

            });
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                //点击确认删除按钮，将全局变量中设置的那个要删除的iD发送到后台
                /*
                $.ajax({
                    url: "/order/" + DELETE_ID + "/delete/", //  /order/123/delete/
                    type: "GET",   // 不用传数据了，id已经放在了url中
                    dataType: "JSON",
                    success: function (res) {
                    }
                })
                */
                $.ajax({
                    url: "/order/delete/", //  /order/delete/?uid=123
                    type: "GET",
                    data:{
                        uid:DELETE_ID
                    },
                    dataType: "JSON",
                    success: function(res){
                    }
                })


            })
        }


    </script>
{% endblock %}

app01/templates/prettynum_list.html
{% extends 'layout.html' %}
{% block content %}

    <div class="container">   <!--这样的话，内容就都放中间了-->
        <div style="margin-bottom:10px">
            <a class="btn btn-primary" href="/prettynum/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建靓号
            </a>

            <a class="btn btn-primary" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建用户ModelForm
            </a>

            <div style="float:right;width:300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                靓号列表
            </div>

            <table class="table table-bordered">

                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>

                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>  <!--在数据库中存的是整型，表头展示的字符串-->
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/prettynum/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/prettynum/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>


    </div>
{% endblock %}